#!/usr/bin/env node
// build.mjs — aggregate scoreboard/entries.json into a ranked, render-ready data
// file the viewer loads (viewer/scoreboard-data.js -> window.SCOREBOARD_DATA).
//
// Ranking mirrors SCOREBOARD.md (b): per problem_id, by the primary verified metric
// (direction per task) with resource-efficiency tie-breaks. No network, no deps.
//
//   node scoreboard/build.mjs           # regenerate viewer/scoreboard-data.js
//   node scoreboard/build.mjs --check   # exit 1 if the committed file is stale
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const data = JSON.parse(readFileSync(join(ROOT, 'scoreboard', 'entries.json'), 'utf8'))

const DIR = { state_prep: 'higher', vqe: 'lower', populations: 'higher', architecture: 'lower', classify: 'higher' }
const TIES = {
  state_prep: ['two_qubit_gates', 'depth'], vqe: ['two_qubit_gates', 'depth'],
  populations: ['two_qubit_gates', 'depth'], architecture: ['edges', 'max_degree'],
  classify: ['feature_map_ops', 'n_qubits'],
}
const num = x => (x === undefined || x === null ? 0 : Number(x))
const fmt = x => (Object.is(x, -0) ? '0' : `${x}`)

function metric(e) {
  const m = e.verified_metric, v = m.value
  switch (e.task) {
    case 'state_prep': return { name: 'fidelity', value: v.toFixed(3), sub: `≥ ${m.threshold} · base ${m.classical_baseline}` }
    case 'vqe': return { name: 'gap', value: v.toFixed(3), sub: `to E₀=${fmt(m.ground_state_energy)} · base ${fmt(m.classical_baseline)}` }
    case 'populations': return { name: `⟨${m.observable || 'X₀X₁'}⟩`, value: `${v >= 0 ? '+' : ''}${v.toFixed(2)}`, sub: `held-out · pops dev ${m.populations_max_deviation ?? 0}` }
    case 'architecture': return { name: 'routing', value: `${v}`, sub: `budget ${m.budget} · base ${m.classical_baseline} · held-out ${m.held_out_routing_cost}` }
    case 'classify': return { name: 'test', value: `${(v * 100).toFixed(0)}%`, sub: `held-out · train ${(m.train_accuracy * 100).toFixed(0)}%` }
    default: return { name: m.name || 'metric', value: `${v}`, sub: '' }
  }
}
function cost(e) {
  const r = e.resource_costs
  if (e.task === 'architecture') return `edges ${r.edges} · deg ${r.max_degree}`
  if (e.task === 'classify') return `ops ${r.feature_map_ops} · ${r.n_qubits} qubit`
  return `2q ${r.two_qubit_gates} · depth ${r.depth}`
}
function rankGroup(list) {
  const t = list[0].task, dir = DIR[t] || 'higher', ties = TIES[t] || []
  return [...list].sort((a, b) => {
    const d = dir === 'higher' ? b.verified_metric.value - a.verified_metric.value
                               : a.verified_metric.value - b.verified_metric.value
    if (Math.abs(d) > 1e-12) return d
    for (const k of ties) { const dd = num(a.resource_costs[k]) - num(b.resource_costs[k]); if (dd) return dd }
    return 0
  })
}

// seeds (entries.json) + auto-discovered run-repo entries (discovered.json), deduped
let discovered = []
try { discovered = JSON.parse(readFileSync(join(ROOT, 'scoreboard', 'discovered.json'), 'utf8')).entries || [] } catch { /* none yet */ }
const seen = new Set()
const allEntries = [...data.entries, ...discovered].filter((e) => {
  const k = `${e.run_repo}|${e.proof_bundle}|${e.problem_id}`
  if (seen.has(k)) return false
  seen.add(k); return true
})

const byProblem = {}
for (const e of allEntries) (byProblem[e.problem_id] ||= []).push(e)
const problems = Object.keys(byProblem)
const rows = []
for (const pid of problems) {
  rankGroup(byProblem[pid]).forEach((e, i) => {
    const m = metric(e)
    rows.push({
      problem_id: e.problem_id, task: e.task, rank: i + 1,
      paradigm_short: e.paradigm_short || e.paradigm.split(/ \(| — /)[0],
      metricName: m.name, metricValue: m.value, metricSub: m.sub,
      costLabel: cost(e), model: e.model,
      bundleUrl: `${e.run_repo}/blob/main/${e.proof_bundle}`,
      why: e.why_it_scores,
      hardware: (e.hardware_reports && e.hardware_reports[0])
        ? { backend: e.hardware_reports[0].backend, metric: e.hardware_reports[0].metric, value: e.hardware_reports[0].value, url: e.hardware_reports[0].report_url }
        : null,
    })
  })
}

const generated = new Date().toISOString().slice(0, 10)
const out = `// GENERATED by scoreboard/build.mjs — do not edit. Run \`node scoreboard/build.mjs\`.\n`
  + `window.SCOREBOARD_DATA = ${JSON.stringify({ generated, count: rows.length, problems, rows }, null, 2)};\n`

const target = join(ROOT, 'viewer', 'scoreboard-data.js')
if (process.argv.includes('--check')) {
  let cur = ''
  try { cur = readFileSync(target, 'utf8') } catch {}
  // ignore the generated-date line when comparing freshness
  const strip = s => s.replace(/"generated":\s*"[^"]*",?\n?/, '')
  if (strip(cur) !== strip(out)) { console.error('STALE: viewer/scoreboard-data.js — run `node scoreboard/build.mjs` and commit.'); process.exit(1) }
  console.log('fresh: viewer/scoreboard-data.js matches entries.json'); process.exit(0)
}
writeFileSync(target, out)
console.log(`wrote viewer/scoreboard-data.js — ${rows.length} entries across ${problems.length} problems`)
